apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: hannah
  labels:
    app: nginx-busybox-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: busybox
      image: busybox #nginx 끊임없이 localhost:80 Health check -> 같은 Pod에서는 localhost 호출 가능
      command: ['sh','-c','while true; do wget -qO- http://localhost:80; sleep 5; done']