apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: hannah
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

# ---기준으로 한파일에서 다른파일로 구분 가능
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: hannah
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hannah
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30102
  selector:
    app: my-nginx