apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: hannah
spec:
  # 인증서 서버 주소. 해당 서버의 리소스를 통해 인증서 발행
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hannahparis@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
# 3. Certificate 생성
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hannah-com-tls
  namespace: hannah
spec: 
  secretName: hannah-com-tls
  duration: 2160h # 90일
  renewBefore: 360h # 15일 전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.dabok.store
  dnsNames:
    - server.dabok.store